### PR TITLE
[FIX #22] Add dependency list

### LINKED ISSUE #22: ModuleNotFoundError: No module named 'yaml'

### PR DESCRIPTION
**Pull request by achillesrasquinha**
For a start, thank you for this library. Also, had been wondering if we could create a `requirements.txt` file instead.

Build failing?

### CODE REVIEW

**Comment by JocelynDelalande** [comment]
@achillesrasquinha thanks :-) why gitpython pandocpy ?

**Comment by achillesrasquinha** [comment]
They seem to be required within `wiki.py`. [Link](https://github.com/redmine-gitlab-migrator/redmine-gitlab-migrator/blob/e35c35ef97afd15d30e8cdb3ecb88207f88a6ea4/redmine_gitlab_migrator/wiki.py#L1)

I had this installed via the `master` branch.

**Comment by achillesrasquinha** [comment]
`pypandoc` would also require Users to have `pandoc` installed. This fails during migration of issues.

**Comment by achillesrasquinha** [comment]
Hi @JocelynDelalande, any update?

**Comment by JocelynDelalande** [comment]
@achillesrasquinha sorry if I gave you expectations with my question, but I'm no longer mainaining this project, sorry.

**Comment by JocelynDelalande** [comment]
(hopefuly, others are maintaining it and will jump in here soon :-)

**Comment by achillesrasquinha** [comment]
That's alright. :smile:

**Comment by kissgyorgy** [comment]
I found these also in #27 .

**Pull request merged**
